apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argo
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 7.3.10
    helm:
      releaseName: grafana
      values: |
        adminUser: admin
        adminPassword: admin123

        grafana.ini:
          server:
            root_url: "https://grafana.come2us.store"
            serve_from_sub_path: true
          session:
            provider: redis
            provider_config: "addr=redis-master.monitoring.svc.cluster.local:6379,password=M0rAuHMl75,db=2,pool_size=100"
            cookie_secure: true
            cookie_samesite: none

        # Grafana를 ALB로 노출하므로 NodePort 불필요
        service:
          type: ClusterIP

        # === Ingress 설정 ===
        ingress:
          enabled: true
          ingressClassName: alb
          annotations:
            kubernetes.io/ingress.class: "alb"
            alb.ingress.kubernetes.io/scheme: internet-facing
            alb.ingress.kubernetes.io/target-type: ip
            alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
            alb.ingress.kubernetes.io/group.name: grafana
            alb.ingress.kubernetes.io/backend-protocol: HTTP
            alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:997784788329:certificate/4f5f4057-92b3-45a3-94e3-13c3d1f873be
            alb.ingress.kubernetes.io/ssl-redirect: "443"
          hosts:
            - grafana.come2us.store
          path: /
          pathType: Prefix

        # === Datasource 자동 등록 ===
        grafana:
          sidecar:
            datasources:
              enabled: true
            dashboards:
              enabled: true

        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Loki
                type: loki
                access: proxy
                url: http://loki-gateway.monitoring.svc.cluster.local # gateway는 80 port 사용
                jsonData:
                  httpHeaderName1: "X-Scope-OrgID"
                secureJsonData:
                  httpHeaderValue1: "1"
              - name: Tempo
                type: tempo
                access: proxy
                url: http://tempo.monitoring.svc.cluster.local:3100
                jsonData:
                  httpMethod: GET
              - name: Prometheus
                type: prometheus
                access: proxy
                url: http://kube-prometheus-kube-prome-prometheus.monitoring.svc:9090
                isDefault: true

        # === Node scheduling ===
        nodeSelector:
          node_type: infra

        tolerations:
          - key: "node_type"
            operator: "Equal"
            value: "infra"
            effect: "NoSchedule"

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
