apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: come2us-jwt-auth
  namespace: come2us
spec:
  jwtRules:
    - issuer: "irum"
      forwardOriginalToken: true
      jwksUri: https://auth.come2us.store/.well-known/jwks.json
