apiVersion: v1
kind: Service
metadata:
  name: {{ include "payment-service.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ include "payment-service.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
  type: {{ .Values.service.type }}
