image:
  tag: "fb748e3"

config:
  PROFILE_ACTIVE: "local"
  MEMBER_HOSTNAME: "member-service"
  MEMBER_PORT: "8081"

  POSTGRESQL_HOST: "postgres.db.svc.cluster.local"
  POSTGRESQL_PORT: "5432"
  DB_NAME: "dev"
  POSTGRESQL_USERNAME: "dev"
  POSTGRESQL_PASSWORD: "dev12345"

  REDIS_HOST: "session-redis.db.svc.cluster.local"
  REDIS_PORT: "6379"

  JWT_ACCESS_TOKEN_EXPIRATION_TIME: "3600"
  JWT_REFRESH_TOKEN_EXPIRATION_TIME: "604800"
  JWT_ISSUER: "irum"
