project: default
source:
  repoURL: 'https://istio-release.storage.googleapis.com/charts'
  targetRevision: 1.28.1
  helm:
    parameters:
      - name: _internal_defaults_do_not_set.autoscaling.enabled
        value: 'true'
    values: |
      autoscaling:
        enabled: true
        minReplicas: 3
        maxReplicas: 12
        targetCPUUtilizationPercentage: 60

      nodeSelector:
        node_type: app

      service:
        type: LoadBalancer
        ports:
          - name: http2
            port: 80
            targetPort: 80
          - name: https
            port: 443
            targetPort: 80
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
          service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
          service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
          service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:ap-northeast-2:997784788329:certificate/4f5f4057-92b3-45a3-94e3-13c3d1f873be"
          service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
  chart: gateway
destination:
  server: 'https://kubernetes.default.svc'
  namespace: istio-system
syncPolicy:
  automated:
    prune: true
    selfHeal: true
