apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "payment-service.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: "1h"

  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}

  target:
    name: {{ include "payment-service.fullname" . }}-secret
    creationPolicy: Owner

  data:
    - secretKey: write-db-password
      remoteRef:
        key: "/{{ .Values.prefix }}/rds/POSTGRESQL_PASSWORD"

    - secretKey: read-db-password
      remoteRef:
        key: "/{{ .Values.prefix }}/rds/POSTGRESQL_PASSWORD"

    - secretKey: toss-secret-key
      remoteRef:
        key: "/{{ .Values.prefix }}/payment/TOSSPAYMENTS_SECRET_KEY"
