apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argo
spec:
  project: default
  source:
    repoURL: 'https://charts.external-secrets.io'
    targetRevision: 0.9.20
    chart: external-secrets
    helm:
      values: |-
        installCRDs: true
        controller:
          create: true
        webhook:
          create: true
        certController:
          create: true
        serviceAccount:
          create: true
          name: external-secrets
          annotations:
            eks.amazonaws.com/role-arn: "arn:aws:iam::997784788329:role/external-secrets-irsa"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-manifests
  namespace: argo
spec:
  project: default
  source:
    repoURL: 'https://github.com/Profect-4th-IRUM/come2us-gitops.git'
    path: cluster
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true