apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-system

commonLabels:
  app: otel-collector

resources:
  - otel-collector-configmap.yaml
  - otel-collector-deployment.yaml
  - otel-collector-service.yaml
