apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: istio-system
data:
  config.yaml: |
    receivers:
      zipkin:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      batch:

    exporters:
      otlp:
        endpoint: tempo.logging.svc.cluster.local:4317
        tls:
          insecure: true
      logging:
        loglevel: debug

    service:
      pipelines:
        traces:
          receivers: [otlp, zipkin]
          processors: [batch]
          exporters: [otlp, logging]
