service:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip

nodeSelector:
  node_type: infra

tolerations:
  - key: node_type
    operator: Equal
    value: infra
    effect: NoSchedule

replicaCount: 2
