image:
  tag: "fb748e3"

config:
  PROFILE_ACTIVE: "prod"
  WRITE_POSTGRESQL_HOST: "come2us-db-primary.cximq62ioqkt.ap-northeast-2.rds.amazonaws.com"
  READ_POSTGRESQL_HOST: "come2us-db-replica.cximq62ioqkt.ap-northeast-2.rds.amazonaws.com"
  DATA_REDIS_HOST: "master.come2us-session-redis.bmp23x.apn2.cache.amazonaws.com"
  CACHE_REDIS_HOST: "come2us-cache-redis.bmp23x.0001.apn2.cache.amazonaws.com"

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1500m"
    memory: "2Gi"

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 55
  scaleDown:
    stabilizationWindowSeconds: 180