apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "product-service.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: "1h"

  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}

  target:
    name: {{ include "product-service.fullname" . }}-secret
    creationPolicy: Owner

  data:
    - secretKey: write-db-password
      remoteRef:
        key: "/{{ .Values.prefix }}/rds/POSTGRESQL_PASSWORD"

    - secretKey: read-db-password
      remoteRef:
        key: "/{{ .Values.prefix }}/rds/POSTGRESQL_PASSWORD"

    - secretKey: redis-password
      remoteRef:
        key: "/{{ .Values.prefix }}/redis/DATA_REDIS_PASSWORD"

    - secretKey: write-postgresql-host
      remoteRef:
        key: "/{{ .Values.prefix }}/rds/WRITE_POSTGRESQL_HOST"

    - secretKey: read-postgresql-host
      remoteRef:
        key: "/{{ .Values.prefix }}/rds/READ_POSTGRESQL_HOST"

    - secretKey: data-redis-host
      remoteRef:
        key: "/{{ .Values.prefix }}/redis/DATA_REDIS_HOST"

    - secretKey: cache-redis-host
      remoteRef:
        key: "/{{ .Values.prefix }}/redis/CACHE_REDIS_HOST"

    - secretKey: kafka-bootstrap-servers
      remoteRef:
        key: "/{{ .Values.prefix }}/msk/KAFKA_BOOTSTRAP_SERVERS"