apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "product-service.fullname" . }}-monitor
  namespace: {{ .Values.monitor.namespace }}
  labels:
    release: {{ .Values.monitor.labels.release }}
spec:
  selector:
    matchLabels:
      app: {{ include "product-service.name" . }}
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  endpoints:
    - port: {{ .Values.service.portName }}
      path: /actuator/prometheus
      interval: 15s